use CGV;

UPDATE SCHEDULE
	JOIN
 SCREEN ON SC_NUM = SD_SC_NUM
SET
	SD_POSSIBLE = SC_SEAT;

# 예약된 좌석 만큼 상영시간에서 예약가능한 좌석수를 빼서 수정하는 쿼리

# 1번 스케쥴에 예매된 좌석 수만큼 1번 스케쥴의 좌석을 수정하는 쿼리
UPDATE
	SCHEDULE
SET
	SD_POSSIBLE = SD_POSSIBLE -(SELECT SUM(TI_ADULT + TI_TEENAGER) FROM TICKETTING WHERE TI_SD_NUM = 1)
WHERE
	SD_NUM = 1;
# 예매가 발생하면 예매한 상황에서 예약 가능한 좌석 수를 수정하는 트리거
DROP TRIGGER IF EXISTS TICKETTING_INSERT;
DELIMITER //
CREATE TRIGGER TICKTTING_INSERT
AFTER INSERT ON TICKETTING
FOR EACH ROW
BEGIN

	# 예매된 성인수와 청소년수 만큼 좌석수를 수정
    UPDATE
		SCHEDULE
	SET
		SD_POSSIBLE = SD_POSSIBLE - (NEW.TI_ADULT + NEW.TI_TEENAGER)
	WHERE
		SD_NUM = NEW.TI_SD_NUM;
END //
DELIMITER ;

INSERT INTO TICKETTING VALUES(NULL, 2, 2, 48000, 'abc123', 2);
